# Exam 1

Reminders:
* Answer questions directly. Extraneous information may result in point deduction.
* Answer easier questions first, then move on to more difficult questions.
* You have at most one hour and fifty minutes to complete this learning exercise.

By typing my name here, I promise I have not committed any act of academic dishonesty including:
1. Copying from a student’s solutions or allowing a student to copy from one’s solutions
2. Using the internet or making phone calls to find solutions
3. Sharing any information about the test with anyone who has not taken it

Student Name: Joshua Carney 


Date: 2/23/2022

**If a code cell has syntax errors, the most you can get is half of its points.**

## Question 1: Program in Python

### Part 1 (10 points)
Define a function to return the longest common prefix of two strings.

The call signature of the function should be

```python
longest_common_prefix(s1, s2)
```
e.g. 
```python
longest_common_prefix('school', 'scholar') 
```
returns a string 'scho'.

In [1]:
def longest_common_prefix(s1, s2):
    # Make sure s1 is the shorter
    if len(s1) > len(s2):
       s1,s2 = s2,s1
    
    longest = ''
    # Start with the entire sequence and shorten
    for x in range(len(s1)):
        prefix = s1[:x]
        if s2.startswith(prefix):
            longest = prefix
    
    # If we haven't returned, there is no common prefix
    return longest

longest_common_prefix('school', 'scholar') 

'scho'

### Part 2 (10 points)

Use the function longest_common_prefix to define a new function that returns the longest common suffix of two strings.

The call signature of the function should be

```python
longest_common_suffix(s1, s2)
```
e.g. 
```python
longest_common_suffix('Kidding', 'King') 
```
returns a string 'ing'.

**To get any points, you must use the function longest_common_prefix**.

**Hint: you can using string slicing to reverse a string.**

In [130]:
def longest_common_suffix(s1, s2):
    # reverse s1 and s2 and then reverse that result from LCP (otherwise the result would be 'gni')
    return longest_common_prefix(s1[::-1], s2[::-1])[::-1]
    

longest_common_suffix('King', 'Kidding') 

'ing'

## Question 2: Map-Reduce (15 points)

If the generator of random variable $X$ is discrete with probability mass function $x_1 \mapsto p_1, x_2 \mapsto p_2, \ldots, x_n \mapsto p_n$ then

$$\operatorname{Var}(X) = \left(\sum_{i=1}^n p_i x_i ^2\right) - \mu^2,$$

where $\mu$ is the average value, i.e.

$$\mu = \sum_{i=1}^n p_i x_i. $$

In the next code cell, compute the average value ($\mu$) and the variance of given $X$ and $P$ using python `map` and `reduce`.

**To get any points, you must use python map and reduce functions.**

In [144]:
X = [5, 1, 2, 3, 1, 2, 5, 4]
P = [0.05, 0.05, 0.15, 0.05, 0.15, 0.2, 0.1, 0.25]

# import what you need first
from operator import mul
from functools import reduce

mew = reduce(lambda x, y: x*y, map(mul, X, P))
vari = reduce(lambda x, y: x*y, map(lambda p, x: p*(x*x), X, P))
print(vari - (mew*mew))

-2.845283203125e-10


## Question 3: Numpy (30 points)

Complete the following code cells as required.

In [5]:
# TO DO (3 points)
# Create a 2-D numpy array [[1, 2, 3, 4]]
import numpy as np
np.arange(1, 4, 1).reshape((1,3))

array([[1, 2, 3]])

In [9]:
# TO DO (3 points)
# Create a 2-D numpy array 
#[[ 1  2  3  4]
#[ 5  6  7  8]
#[ 9 10 11 12]]

x = np.arange(1, 13, 1).reshape((3,4))
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# TO DO (3 points)
# reshape the above array to a 4-row, 3-col array
x = x.reshape((4,3))
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
# TO DO (3 points)
# split the above array to two subarrays using a split function: 
#[[1, 2, 3], [4, 5, 6], [7, 8, 9]]  and [[10, 11, 12]]
y1, y2, y3 = np.vsplit(x, [3, 4])
print(y1)
print(y2)
# TO DO (2 points)
# Use array slicing to get the same subarrays
print(x[0:3])
print(x[3:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]]


In [48]:
# TO DO (2 points)
# create a 1-D numpy array [0, 1, 2, 3, 4, 5, 6, 7, 8]
z = np.arange(9)
print(z)


# TO DO (3 points)
#Use fancy indexing to create the following 2-D array from the above 1-D array
#[[1 2]
#[3 4]]
#You must use fancy indexing to get any points
indices = np.array([[1,2],[3,4]])
print(z[indices])


[0 1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]]


In [54]:
# TO DO (3 points)
# create a 1-D numpy array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
# Then reshape it to (3, 4)

arr = np.arange(1, 13, 1).reshape(3,4)
print(arr)
print('====')
# TO DO (3 points)
#Use fancy indexing to get the last two rows of the reshaped array
#You must use fancy indexing to get any points

print(arr[np.array([1, 2])])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
====
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
# TO DO (2 points)
# Create an 4x4 array filled with random integers from range [0, 10)
# hint: Use randint
arr2 = np.random.randint(0, 10, (4,4))
print(arr2)
# TO DO (3 points)
#Use boolean array as mask to find all the elements < 5 from the above array
print(arr2[arr2 < 5])


[[6 9 4 3]
 [3 1 3 9]
 [1 8 0 4]
 [4 5 5 9]]
[4 3 3 1 3 1 0 4 4]


## Question 4: Pandas (35 points)

Complete the following code cells as required.

In [90]:
# TO DO (2 points)
# Read the csv file 'car-sales.csv' as a pandas dataframe 
# and show the first 10 records
import pandas as pd
df = pd.read_csv('car-sales.csv')
df.head(10)

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [91]:
# TO DO (3 points)
# Change the names of all columns to uppercase
df = df.rename(columns=str.upper)
df.head()

MAKE COLOUR  ODOMETER (KM)  DOORS    PRICE
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [92]:
# TO DO (2 points)
# Use one line of code to find the total number of records
df.count()

MAKE             951
COLOUR           950
ODOMETER (KM)    950
DOORS            950
PRICE            950
dtype: int64

In [93]:
# Extra: 5 Points
# drop all the rows with missing values in MAKE
df.dropna(subset='MAKE', inplace=True)

In [95]:
# TO DO (5 points)
# Fill missing values in ODOMETER (KM) with the mean value of ODOMETER (KM)
# why
df = df['ODOMETER (KM)'].fillna(df.mean('ODOMETER (KM)'), inplace=True)
# TO DO (3 points)
# Fill missing values in PRICE with the mean value of PRICE
df.fillna(df.PRICE)


ValueError: No axis named ODOMETER (KM) for object type DataFrame

In [100]:
# TO DO (3 points)
# Get a new pandas DataFrame only contains four columns: MAKE, COLOUR, ODOMETER (KM), and PRICE
# To get any points, DO NOT drop 'DOORS'.
df2 = df[["MAKE", "COLOUR", "ODOMETER (KM)", "PRICE"]]
df2

MAKE COLOUR  ODOMETER (KM)    PRICE
0     Honda  White        35431.0  15323.0
1       BMW   Blue       192714.0  19943.0
2     Honda  White        84714.0  28343.0
3    Toyota  White       154365.0  13434.0
4    Nissan   Blue       181577.0  14043.0
..      ...    ...            ...      ...
994     BMW   Blue       163322.0  31666.0
995  Toyota  Black        35820.0  32042.0
997  Nissan   Blue        66604.0  31570.0
998   Honda  White       215883.0   4001.0
999  Toyota   Blue       248360.0  12732.0

[773 rows x 4 columns]

In [101]:
# TO DO (2 points)
# Drop missing values from the DataFrame above
df2.dropna(inplace=True)

/var/folders/4q/v53r629s5wv9h1ph62srxwsm0000gn/T/ipykernel_89381/2654060851.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(inplace=True)


In [102]:
# TO DO (5 points)
# Use boolean array as mask to find all records of price < 3500
df2[df2['PRICE'] < 3500]

MAKE COLOUR  ODOMETER (KM)   PRICE
173  Nissan  Black       240536.0  3247.0
757  Nissan   Blue       233501.0  2796.0
845  Toyota  Green       243177.0  3125.0

In [103]:
# TO DO (5 points)
# Find the most expensive three cars
df2.sort_values(by='PRICE').head(3)

MAKE COLOUR  ODOMETER (KM)   PRICE
757  Nissan   Blue       233501.0  2796.0
845  Toyota  Green       243177.0  3125.0
173  Nissan  Black       240536.0  3247.0

In [128]:
# TO DO (5 points)
# Find the most popular 'MAKE'
s = df2['MAKE'].value_counts()
m = s.max()
s[df2['MAKE'].value_counts() == m]

Toyota    306
Name: MAKE, dtype: int64