# Lab 3: Understanding NumPy Array

<hr>

In [2]:
# Creating an array [2, 4, 6, 8, 10]
# TO DO



In [2]:
import numpy as np
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [3]:
# Create an 3x3 array of all zeros


# Create an 2x2 array of all ones


# Create a 2x2 constant array of all 8


# Create a 4x4 identity matrix


 # Create an 3x3 array filled with random values


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[8 8]
 [8 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.59042375 0.96644986 0.28002982]
 [0.08218806 0.16863101 0.17559191]
 [0.08850536 0.65224573 0.04857833]]


In [16]:
print(np.zeros((3,3)))
print(np.ones((2,2)))
print(np.full((2,2), 8))
print(np.eye(4))
print(np.random.random((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[8 8]
 [8 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.25176553 0.14072376 0.95441109]
 [0.75404006 0.27344515 0.772937  ]
 [0.97626435 0.61055273 0.88710606]]


In [5]:
# Creating array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] using arange() 
# TO DO


[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
arr = np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# check shape of Array the above array
# TO DO


(10,)

In [6]:
np.shape(arr)

(10,)

In [6]:
#Create a 2-D array [[5, 6], [7, 8]]
# TO DO

[[5 6]
 [7 8]]


In [13]:
a = np.arange(5, 9, 1)
a = a.reshape((2,2))
print(a)

[[5 6]
 [7 8]]


In [14]:
print(a[0,1])

6


In [15]:
print(a[1,0])

7


In [16]:
print(a[1,1])

8


## Manipulating Shape of NumPy Array

In [17]:
# Create an array
arr = np.arange(12)

In [9]:
# Reshape the array dimension to 4x3
# TO DO

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
arr = arr.reshape((4,3))
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
# Reshape the array dimension to 3x4
# TO DO


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
new_arr = arr.reshape((3,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
# flatten the array 

print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
arr = np.arange(12)
arr = arr.reshape(3, 4)
print(arr)
# Transpose the matrix arr
# TO DO





[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
arr = arr.T
print(arr)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Stacking of Numpy arrays

In [25]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr2 = 2*arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [56]:
#Horizontal stacking arr1 and arr2 using hstack()
# TO DO


[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [27]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [59]:
# Horizontal stacking arr1 and arr2 using concatenate() function
# TO DO



[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [30]:
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [31]:
# Vertical stacking arr1 and arr2 using vstack() function
# TO DO
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [61]:
# Vertical stacking using concatenate() function
# TO DO


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [32]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [33]:
# Create 1-D array
arr1 = np.arange(4,7) 
print(arr1)

[4 5 6]


In [34]:
# Create 1-D array
arr2 = 2 * arr1
print(arr2)

[ 8 10 12]


In [4]:
# Use column_stack to create a 2-D array [[4, 8], [5, 10], [6, 12]]
# TO DO



[[ 4  8]
 [ 5 10]
 [ 6 12]]


In [35]:
np.column_stack((arr1, arr2))

array([[ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [68]:
# Use row stack to create a 2-D array [[4, 5, 6], [8, 10, 12]]
# TO DO



[[ 4  5  6]
 [ 8 10 12]]


In [36]:
np.row_stack((arr1, arr2))

array([[ 4,  5,  6],
       [ 8, 10, 12]])

## Partitioning Numpy Array

In [37]:
# Create an array
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Peroform horizontal splitting to get [array([[1],[4],[7]]), array([[2],[5],[8]]), array([[3],[6],[9]])]
# TO DO



[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [39]:
np.hsplit(arr, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [20]:
# vertical split arr to get [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
# TO DO



[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [40]:
np.vsplit(arr, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [21]:
# split with axis=0 to get [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
# TO DO


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [41]:
np.split(arr, 3, 0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [22]:
# split with axis=1 to get [array([[1],[4],[7]]), array([[2],[5],[8]]), array([[3],[6],[9]])]
# TO DO



[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [42]:
np.split(arr, 3, 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

## Changing Datatype of NumPy Arrays

In [43]:
# Create an array
arr=np.arange(1,10).reshape(3,3)
print("Integer Array:",arr)

# Change datatype of array
arr=arr.astype(float)

# print array
print("Float Array:", arr)

# Check new data type of array
print("Changed Datatype:", arr.dtype)

Integer Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Float Array: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Changed Datatype: float64


In [45]:
# Create an array
arr=np.arange(1,10)

# Convert NumPy array arr to Python List
# TO DO



In [46]:
list(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## Creating NumPy views and copies

In [47]:
# Create NumPy Array
arr = np.arange(1,5).reshape(2,2)
print(arr)

# Create no copy only assignment
arr_no_copy=arr

# Create Deep Copy
arr_copy=arr.copy()

# Create shallow copy using View
arr_view=arr.view()

print("Original Array: ",id(arr))
print("Assignment: ",id(arr_no_copy))
print("Deep Copy: ",id(arr_copy))
print("Shallow Copy(View): ",id(arr_view))

[[1 2]
 [3 4]]
Original Array:  4479772112
Assignment:  4479772112
Deep Copy:  4464507856
Shallow Copy(View):  4581307184


In [48]:
# Update the values of original array
arr[1]=[99,89]

# Check values of array view
print("View Array:\n", arr_view)

# Check values of array copy
print("Copied Array:\n", arr_copy)

View Array:
 [[ 1  2]
 [99 89]]
Copied Array:
 [[1 2]
 [3 4]]


## Slicing NumPy Array

In [49]:
# Create NumPy Array
arr = np.arange(12) 
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
# Slice arr to get [3 4 5]
# TO DO


[3 4 5]


In [51]:
arr[3:6]

array([3, 4, 5])

In [55]:
# Slice arr to get [ 3  4  5  6  7  8  9 10 11]
# TO DO



[ 3  4  5  6  7  8  9 10 11]


In [52]:
arr[3:12]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
# Slice arr to get [ 9 10 11]
# TO DO


[ 9 10 11]


In [53]:
arr[9:12]

array([ 9, 10, 11])

In [57]:
# Slice arr to get [2 4 6]
# TO DO



[2 4 6]


In [56]:
arr[2:7:2]

array([2, 4, 6])

In [68]:
arr = arr.reshape(4, 3)
# Slice arr to get array([[1, 2],[4, 5],[7, 8]])
# TO DO

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
arr[1:3, 1:3]

array([[4, 5],
       [7, 8]])

## Boolean and Fancy Indexing

In [72]:
# Create NumPy Array
arr = np.arange(21,41,2)
print("Orignial Array:\n",arr)

# Use Boolean array as mask to print all elements > 30
# TO DO



Orignial Array:
 [21 23 25 27 29 31 33 35 37 39]


In [75]:
arr = np.arange(21,41,2)
print("Orignial Array:\n",arr)

arr[arr > 30]

Orignial Array:
 [21 23 25 27 29 31 33 35 37 39]


array([31, 33, 35, 37, 39])

In [60]:
# Create NumPy Array
arr = np.arange(1,21).reshape(5,4)
print("Orignial Array:\n",arr)

# Use Fancy Indexing to Select 2nd and 3rd row
# TO DO


# Use Fancy Indexing to Select 3nd and 4th row
# TO DO


Orignial Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Selected 1st and 2nd Row:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Selected 3rd and 4th Row:
 [[ 9 10 11 12]
 [13 14 15 16]]


In [79]:
# Use Fancy Indexing to get [ 7 12 20] from arr
# TO DO
arr = np.arange(1,21).reshape(5,4)
print("Orignial Array:\n",arr)



Orignial Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## Broadcasting arrays

In [80]:
# Create NumPy Array
arr1 = np.arange(1,5).reshape(2,2) 
print(arr1)

[[1 2]
 [3 4]]


In [81]:
# Create another NumPy Array
arr2 = [6, 6]

In [69]:
# Add two matrices arr1 and arr2 (think what the output is)
# TO DO


[[ 7  8]
 [ 9 10]]


In [82]:
arr1 + arr2

array([[ 7,  8],
       [ 9, 10]])

In [70]:
# Multiply two matrices arr1 and arr2 (think what the output is)
# TO DO


[[ 6 12]
 [18 24]]


In [83]:
arr1 * arr2

array([[ 6, 12],
       [18, 24]])

In [71]:
# Add a scaler value 3 to arr1
# TO DO


[[4 5]
 [6 7]]


In [84]:
arr1 + 3

array([[4, 5],
       [6, 7]])

In [88]:
# Multiply with a scalar value 3 to arr1
# TO DO


[[ 3  6]
 [ 9 12]]


In [85]:
arr1 * 3

array([[ 3,  6],
       [ 9, 12]])

In [86]:
# Before running the cell, think what a and b are.
a=np.arange(2, 5)
b=np.arange(2, 5)[:,np.newaxis]

In [87]:
#What is a*b (broadcasting)
a*b

array([[ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16]])